ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS customer_note TEXT NOT NULL DEFAULT '';

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS note VARCHAR(300);

ALTER TABLE invoice_revisions
  ADD COLUMN IF NOT EXISTS old_customer_note TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS new_customer_note TEXT NOT NULL DEFAULT '';
